#!/usr/bin/env bash
# ============================================================================
# One-command Supabase provisioning for a new client backend.
#
# Assembles the full setup SQL from the single sources of truth in docs/
# (DATABASE_SCHEMA.md + SECURE_ACCESS.md) plus the base workspaces table,
# substitutes THIS client's workspace name into the login RPCs, and either
# applies it directly (if a DB connection string is given) or writes a
# ready-to-paste setup.sql for the Supabase SQL editor.
#
# Usage:
#   ./supabase/setup/provision.sh                 # workspace read from config.js
#   ./supabase/setup/provision.sh their-company   # explicit workspace name
#   SUPABASE_DB_URL='postgresql://postgres:PW@HOST:5432/postgres' \
#       ./supabase/setup/provision.sh their-company   # apply directly via psql
#
# The connection string is in your Supabase dashboard:
#   Project Settings -> Database -> Connection string (URI).
# ============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"

# Workspace name: pass it explicitly as the 1st arg (recommended — config.js is
# multi-tenant). With no arg, falls back to the FIRST tenant's workspace in config.js.
WS="${1:-}"
if [ -z "$WS" ] && [ -f "$ROOT/config.js" ]; then
  WS="$(grep -oE 'workspace:[[:space:]]*"[^"]+"' "$ROOT/config.js" | head -1 | sed -E 's/.*"([^"]+)".*/\1/')"
fi
if [ -z "$WS" ]; then
  echo "ERROR: could not determine the workspace name."
  echo "Pass it explicitly:  $0 <workspace-name>"
  exit 1
fi

OUT="$HERE/build"; mkdir -p "$OUT"
SQL="$OUT/setup.sql"

# Extract the single fenced ```sql block from a markdown doc.
extract_sql() { awk '/^```sql/{f=1;next} /^```/{if(f)exit} f' "$1"; }

{
  echo "-- ============================================================"
  echo "-- Supabase setup for workspace: $WS"
  echo "-- Generated by supabase/setup/provision.sh — do not edit by hand."
  echo "-- Idempotent: safe to re-run (create if not exists / create or replace)."
  echo "-- ============================================================"
  echo
  cat "$HERE/00_workspaces.sql"
  echo
  echo "-- ===== Per-record tables (docs/DATABASE_SCHEMA.md) ====="
  extract_sql "$ROOT/docs/DATABASE_SCHEMA.md"
  echo
  echo "-- ===== RLS lockdown + login RPCs (docs/SECURE_ACCESS.md) ====="
  echo "-- Login RPCs are bound to this client's workspace id ('$WS')."
  extract_sql "$ROOT/docs/SECURE_ACCESS.md" | sed "s/id = 'island-explorer'/id = '$WS'/g"
} > "$SQL"

# Sanity check: the workspace substitution must have taken (the RPCs read the blob).
if grep -q "id = 'island-explorer'" "$SQL" && [ "$WS" != "island-explorer" ]; then
  echo "ERROR: workspace substitution failed — 'island-explorer' still present in $SQL" >&2
  exit 1
fi

echo "Generated: $SQL"
echo "Workspace: $WS"
echo "Contains:  $(grep -c 'create table if not exists' "$SQL") tables, $(grep -c 'create or replace function' "$SQL") RPCs"

if [ -n "${SUPABASE_DB_URL:-}" ]; then
  if ! command -v psql >/dev/null 2>&1; then
    echo "psql not found. Install postgresql-client, or paste $SQL into the Supabase SQL editor." >&2
    exit 1
  fi
  echo "Applying to database…"
  psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f "$SQL"
  echo "Done — backend provisioned for '$WS'."
else
  echo
  echo "Nothing was applied (no SUPABASE_DB_URL set). To finish, either:"
  echo "  A) Supabase dashboard -> SQL Editor -> paste the contents of:"
  echo "        $SQL"
  echo "     and click Run; or"
  echo "  B) Re-run with a connection string to apply automatically:"
  echo "        SUPABASE_DB_URL='postgresql://postgres:PW@HOST:5432/postgres' $0 $WS"
  echo
  echo "After running the SQL, create your team's login(s) in Supabase -> Authentication -> Users"
  echo "(or via the console's Create-account screen). Only signed-in team users can read/write data."
fi
